events {
  worker_connections 1024;
}

http {
  upstream journal { server api-journal:3001; }
  upstream report  { server api-report:3002; }

  server {
    listen 80;
    server_name _;

    client_max_body_size 10m;

    location /api/journal/ {
      rewrite ^/api/journal/(.*)$ /api/$1 break;
      proxy_pass http://journal;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/report/ {
      rewrite ^/api/report/(.*)$ /api/$1 break;
      proxy_pass http://report;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
